### ISSUE TITLE
Removing background feature is not working

### ISSUE THREAD

**Issue by Yehoward** [LyoSU/fStikBot#264]
When I try to remove the background of an image with `/clear` it adds the image I sent to selected stickerpack, instead of sending me back the image without a background.
Am I doing something wrong or is it a bug?

**Comment by LyoSU** [comment]
Have you tried sending the command again? Did you remember to select a model?

**Comment by Yehoward** [comment]
![image](https://github.com/LyoSU/fStikBot/assets/88189319/3430fb62-ea24-465a-8a8d-ca107506ff52)

**Comment by LyoSU** [comment]
you are sending the file. For people like you, he even stressed that you need a photo

**Comment by Yehoward** [comment]
> you are sending the file. For people like you, he even stressed that you need a photo

I am so sorry, thank you so much!
