### ISSUE TITLE
Hdh

### ISSUE THREAD

**Issue by Rumeys5** [LyoSU/fStikBot#70]
![IMG_20211220_202745_225.jpg](https://user-images.githubusercontent.com/94923014/146981213-edc0c35d-8698-4da4-a653-2a5ec55b2b04.jpg)

**Comment by Rumeys5** [comment]
T

**Comment by Dubzer** [comment]
нет блин Y
![image](https://user-images.githubusercontent.com/18244287/147265285-b2ae27e7-b6c6-4197-9d09-850dbb0bbfd2.png)

**Comment by pacificescape** [comment]
![BDE7E229-1766-4C77-929D-68657ACC521F](https://user-images.githubusercontent.com/17690123/147265583-a5a3ed06-89ff-43a8-a241-c790b92a644e.jpeg)
