### ISSUE TITLE
Only first emoji is applied to sticker

### ISSUE THREAD

**Issue by hatkidchan** [LyoSU/fStikBot#94]
When adding new sticker and bot asks for corresponding emojis, sending multiple emojis at the same time saves only first of them

![image](https://user-images.githubusercontent.com/35804000/152851416-1d40a101-5654-4ba5-911c-c8abbe1d3bc2.png)
![image](https://user-images.githubusercontent.com/35804000/152851447-97b0c2a5-b86d-4528-a66d-9cc8b12e332a.png)

**Comment by LyoSU** [comment]
fixed
